### ISSUE TITLE
how to use ?

### ISSUE THREAD

**Issue by wenxingxing** [sun2ot/ClashRules#1]
本地部署subconverter吗？

**Comment by sun2ot** [comment]
> 

手动改配置文件就把readme的provider和rule粘贴进去就行了。

如果你有subconverter的话，把 `config/test.ini` 放到配置文件目录下引用就可以了。

或者找个现成的订阅转换网站，然后引用远程配置 `https://raw.githubusercontent.com/sun2ot/ClashRules/main/config/test.ini`

**Comment by sun2ot** [comment]
已更新详细使用方法，见 [README](https://github.com/sun2ot/ClashRules#readme)

**Comment by wenxingxing** [comment]
thx
