### ISSUE TITLE
推荐个去广告规则

### ISSUE THREAD

**Issue by a39908646** [sun2ot/ClashRules#3]
推荐个秋风的https://github.com/TG-Twilight/AWAvenue-Ads-Rule

**Comment by sun2ot** [comment]
已添加 [anti-ad.ini](https://github.com/sun2ot/ClashRules/commit/16c71cf917488028bc8395907a06658fc75ea57f#diff-003da7931247f438ac1024c91c375851c0867d765b63b7bdf7eb2077260ff4bf)
