### ISSUE TITLE
cnip.yaml 内有重复

### ISSUE THREAD

**Issue by Shayne-iaMi** [sun2ot/ClashRules#4]
检查了库里提供的文件，似乎是内容出现了两遍。导致读取到两次key word: 'payload'报错，无法切换到profile

**Comment by sun2ot** [comment]
确实存在该问题，不过很奇怪我这的clash verge rev一直没报错，所以没注意到。已修复。

**Comment by Shayne-iaMi** [comment]
嗯嗯问题不大，我下载到本地去重之后再改一下配置文件也ok了，就是这里report一下
